# Generated by Django 5.1.1 on 2024-10-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LehenAplikazioa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikasgaiak',
            fields=[
                ('ikasgai_kodea', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('maila', models.CharField(max_length=50)),
                ('hizkuntza', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ikasle',
            name='jaiotze_data',
        ),
        migrations.CreateModel(
            name='Notak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ikasgai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LehenAplikazioa.ikasgaiak')),
                ('ikasle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LehenAplikazioa.ikasle')),
            ],
        ),
    ]
